### ISSUE TITLE
kubeadm_token isn't created

### ISSUE THREAD

**Issue by johnstudarus** [packet-labs/kubernetes-bgp#1]
By default, TF is asking for a token when run rather than creating a new one if one isn't provided. There is ./scripts/kubeadm-token.sh which generates a token that's being passed to the minions. And then there's variables.kubeadm_token being written to the configuration file. Are there two different tokens being used?

**Comment by pereztr5** [comment]
Thanks John I have made these changes and removed the need to define a kubeadm token since this will auto generate it.
