### ISSUE TITLE
Resource "packet_project" not found

### ISSUE THREAD

**Issue by BenSchZA** [packet-labs/kubernetes-bgp#13]
After setting the auth token, and the other available variables, I get the following error:

```
Error: Not found

  on main.tf line 5, in resource "packet_project" "kubenet":
   5: resource "packet_project" "kubenet" {
```

Is there maybe a step missing in the README? I've tried setting the name to my project name, and even applied @enkelprifti98 PR.

**Comment by BenSchZA** [comment]
It seems to be an issue with the Terraform provider rather than this repo itself.

**Comment by vielmetti** [comment]
Looking into this @BenSchZA !

**Comment by BenSchZA** [comment]
Using Terraform 0.12 for reference. Came across this issue in my search: https://github.com/terraform-providers/terraform-provider-packet/issues/45 

Wasn't able to, if it's even possible yet, import the resource either. I have a pretty simple setup with a single organization and project.

**Comment by BenSchZA** [comment]
Let me know if I can give any other context or debugging steps :)

**Comment by enkelprifti98** [comment]
@BenSchZA Which packet provider version are you using for TF?

**Comment by BenSchZA** [comment]
@enkelprifti98 Good question! I see it's not defined in the repo, probably should be fixed.

```
Terraform v0.12.20
+ provider.external v1.2.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.packet v2.9.0
+ provider.template v2.1.2
+ provider.tls v2.1.1
```

**Comment by BenSchZA** [comment]
I just gave it another try, and now it says: `Error: You are not authorized to view this organization` which seems like an auth token issue. I've used this same auth token to deploy using Terraform from another repo - maybe I'll try compare the config there.

**Comment by BenSchZA** [comment]
This was the repo that had no issue, but it doesn't require the `packet_project` resource with organization ID: https://github.com/packet-labs/packet-k3s

**Comment by vielmetti** [comment]
@BenSchZA is the token a "personal API token" or a "project API token" ? There is a brief writeup of the distinction here: https://www.packet.com/developers/changelog/project-only-api-keys/

**Comment by BenSchZA** [comment]
It's a project API token. Thanks for the distinction. Should I create a personal API token?

**Comment by t0mk** [comment]
Hi @BenSchZA are you creating the project form terraform or are you using an existing project?

If you're using existing project, you can only use the project ID as variable, you don't have to decare the resoruce I think.

**Comment by BenSchZA** [comment]
I'm using an existing project. The resource is used throughout this repo though, but I suppose I could just replace it with the project ID. I'll give that a try.

**Comment by BenSchZA** [comment]
After replacing all the references with a Terraform var for project ID, it worked :) Now to see if the cluster works.

**Comment by BenSchZA** [comment]
Ran into an issue because the bash scripts reference `/bin/bash` which doesn't exist on my system :P Joys of Nix. And it requires jq. Will make a PR to note that.

```

Error: failed to execute "./scripts/kubeadm-token.sh": fork/exec ./scripts/kubeadm-token.sh: no such file or directory

  on controller.tf line 59, in data "external" "kubeadm_join":
  59: data "external" "kubeadm_join" {



Error: Access denied for the current authentication token

  on metallb.tf line 9, in resource "packet_bgp_session" "kube_bgp":
   9: resource "packet_bgp_session" "kube_bgp" {



Error: failed to execute "./scripts/gateway.sh": fork/exec ./scripts/gateway.sh: no such file or directory

  on nodes.tf line 71, in data "external" "private_ipv4_gateway":
  71: data "external" "private_ipv4_gateway" {
```

**Comment by enkelprifti98** [comment]
@BenSchZA I would recommend using your personal API token as project API tokens aren't able to do certain things such as BGP sessions.

**Comment by t0mk** [comment]
> After setting the auth token, and the other available variables, I get the following error:
> 
> ```
> Error: Not found
> 
>   on main.tf line 5, in resource "packet_project" "kubenet":
>    5: resource "packet_project" "kubenet" {
> ```
> 
> Is there maybe a step missing in the README? I've tried setting the name to my project name, and even applied @enkelprifti98 PR.

The terraform templates will attempt to create a new project, no matter what kind of name you will put there. The name will be used for the created project. Project name doesn't have to be unique, so even if you put there a name of an existing project, it should create a new one (with the same name, so probably not a good idea). 

The TF code in this repo doesn't attempt to reuse project, unless you modify it like you did.

I think it's still not clear why you had "Not Found" returned by the API. It could have happened if you ran `terraform apply` (creating the new project), and then manually removed the project, and then ran `terraform apply` again. Because terraform is storing the ID of the new project in local file, and always uses the ID for fetching the (any) resource from the API, never a name.

**Comment by BenSchZA** [comment]
> > After setting the auth token, and the other available variables, I get the following error:
> > ```
> > Error: Not found
> > 
> >   on main.tf line 5, in resource "packet_project" "kubenet":
> >    5: resource "packet_project" "kubenet" {
> > ```
> > 
> > 
> > Is there maybe a step missing in the README? I've tried setting the name to my project name, and even applied @enkelprifti98 PR.
> 
> The terraform templates will attempt to create a new project, no matter what kind of name you will put there. The name will be used for the created project. Project name doesn't have to be unique, so even if you put there a name of an existing project, it should create a new one (with the same name, so probably not a good idea).
> 
> The TF code in this repo doesn't attempt to reuse project, unless you modify it like you did.
> 
> I think it's still not clear why you had "Not Found" returned by the API. It could have happened if you ran `terraform apply` (creating the new project), and then manually removed the project, and then ran `terraform apply` again. Because terraform is storing the ID of the new project in local file, and always uses the ID for fetching the (any) resource from the API, never a name.

I think in the end the issue wasn't that I modified it or that I did any manual actions, but that I used a project API key instead of a personal API key, which makes sense, but isn't something that's obvious to someone new to the platform.

Really appreciate the quick response and guidance :) Happy to close this.
